// export const PinsTypes = {
//     FETCH_PINS_BY_PAGE_NUM_INIT : 'FETCH_PINS_BY_PAGE_NUM_INIT',
//     FETCH_PINS_BY_PAGE_NUM_SUCCESS : 'FETCH_PINS_BY_PAGE_NUM_SUCCESS',
//     FETCH_PINS_BY_PAGE_NUM_FAILED : 'FETCH_PINS_BY_PAGE_NUM_Failed',
//     FETCH_MORE_PINS_ON_SCROLL_INIT : 'FETCH_MORE_PINS_ON_SCROLL_INIT'

// }

export const PinsTypes ={
    FETCH_PINS_INIT : "FETCH_PINS_INIT",
    FETCH_PINS_SUCCESS : "FETCH_PINS_SUCCESS",
    FETCH_PINS_FAIL : "FETCH_PINS_FAIL",  
    FETCH_PINS_ONSCROLL_INIT : "FETCH_PINS_ONSCROLL_INIT",
    FETCH_PINS_ONSCROLL_SUCCESS : "FETCH_PINS_ONSCROLL_SUCCESS",
    FETCH_PINS_ONSCROLL_FAIL : "FETCH_PINS_ONSCROLL_FAIL",  
}